name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag limebite-back:latest 
    - name: deploy image on server 
      run: cd /home/ubuntu/backend && docker compose down && docker compose up -d
